name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * *' # Her gün 00:00'da çalıştır

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "ahmetcarrdak"
          git config --global user.email "ahmetcarrdak@icloud.com"

      - name: Create commit
        run: |
          echo "Auto commit" >> commit.txt
          git add commit.txt
          git commit -m "Auto commit"
          git push
